// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DependenciesRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DependenciesRequest) Reset()         { *m = DependenciesRequest{} }
func (m *DependenciesRequest) String() string { return proto.CompactTextString(m) }
func (*DependenciesRequest) ProtoMessage()    {}
func (*DependenciesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52fff2e9b74eb1d1, []int{0}
}

func (m *DependenciesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DependenciesRequest.Unmarshal(m, b)
}
func (m *DependenciesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DependenciesRequest.Marshal(b, m, deterministic)
}
func (m *DependenciesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DependenciesRequest.Merge(m, src)
}
func (m *DependenciesRequest) XXX_Size() int {
	return xxx_messageInfo_DependenciesRequest.Size(m)
}
func (m *DependenciesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DependenciesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DependenciesRequest proto.InternalMessageInfo

func (m *DependenciesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DependenciesRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Dependency struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string        `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Dependencies         []*Dependency `protobuf:"bytes,3,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Dependency) Reset()         { *m = Dependency{} }
func (m *Dependency) String() string { return proto.CompactTextString(m) }
func (*Dependency) ProtoMessage()    {}
func (*Dependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_52fff2e9b74eb1d1, []int{1}
}

func (m *Dependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dependency.Unmarshal(m, b)
}
func (m *Dependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dependency.Marshal(b, m, deterministic)
}
func (m *Dependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dependency.Merge(m, src)
}
func (m *Dependency) XXX_Size() int {
	return xxx_messageInfo_Dependency.Size(m)
}
func (m *Dependency) XXX_DiscardUnknown() {
	xxx_messageInfo_Dependency.DiscardUnknown(m)
}

var xxx_messageInfo_Dependency proto.InternalMessageInfo

func (m *Dependency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Dependency) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Dependency) GetDependencies() []*Dependency {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type DependenciesResponse struct {
	Dependencies         *Dependency `protobuf:"bytes,1,opt,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DependenciesResponse) Reset()         { *m = DependenciesResponse{} }
func (m *DependenciesResponse) String() string { return proto.CompactTextString(m) }
func (*DependenciesResponse) ProtoMessage()    {}
func (*DependenciesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52fff2e9b74eb1d1, []int{2}
}

func (m *DependenciesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DependenciesResponse.Unmarshal(m, b)
}
func (m *DependenciesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DependenciesResponse.Marshal(b, m, deterministic)
}
func (m *DependenciesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DependenciesResponse.Merge(m, src)
}
func (m *DependenciesResponse) XXX_Size() int {
	return xxx_messageInfo_DependenciesResponse.Size(m)
}
func (m *DependenciesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DependenciesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DependenciesResponse proto.InternalMessageInfo

func (m *DependenciesResponse) GetDependencies() *Dependency {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func init() {
	proto.RegisterType((*DependenciesRequest)(nil), "api.DependenciesRequest")
	proto.RegisterType((*Dependency)(nil), "api.Dependency")
	proto.RegisterType((*DependenciesResponse)(nil), "api.DependenciesResponse")
}

func init() { proto.RegisterFile("internal/api/api.proto", fileDescriptor_52fff2e9b74eb1d1) }

var fileDescriptor_52fff2e9b74eb1d1 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x4f, 0x2c, 0xc8, 0x04, 0x61, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c,
	0x21, 0xe6, 0xc4, 0x82, 0x4c, 0x25, 0x67, 0x2e, 0x61, 0x97, 0xd4, 0x82, 0xd4, 0xbc, 0x94, 0xd4,
	0xbc, 0xe4, 0xcc, 0xd4, 0xe2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96,
	0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x48, 0x82, 0x8b,
	0xbd, 0x2c, 0xb5, 0xa8, 0x38, 0x33, 0x3f, 0x4f, 0x82, 0x09, 0x2c, 0x0c, 0xe3, 0x2a, 0xe5, 0x73,
	0x71, 0xc1, 0x0d, 0xa9, 0x24, 0x4d, 0xaf, 0x90, 0x31, 0x17, 0x4f, 0x0a, 0x92, 0x03, 0x24, 0x98,
	0x15, 0x98, 0x35, 0xb8, 0x8d, 0xf8, 0xf5, 0x40, 0xee, 0x44, 0x18, 0x1a, 0x84, 0xa2, 0x48, 0xc9,
	0x9b, 0x4b, 0x04, 0xd5, 0xd5, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x18, 0x86, 0x81, 0x9c, 0x40,
	0xc8, 0x30, 0xa3, 0x78, 0xd4, 0x20, 0x08, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xf2, 0xe0,
	0xe2, 0x77, 0x4f, 0x2d, 0x41, 0x96, 0x11, 0x92, 0x40, 0x35, 0x08, 0x11, 0x5e, 0x52, 0x92, 0x58,
	0x64, 0x20, 0x6e, 0x52, 0x62, 0x48, 0x62, 0x03, 0x87, 0xb7, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x7d, 0xbb, 0xe1, 0x60, 0x89, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DependenciesServiceClient is the client API for DependenciesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DependenciesServiceClient interface {
	GetDependencies(ctx context.Context, in *DependenciesRequest, opts ...grpc.CallOption) (*DependenciesResponse, error)
}

type dependenciesServiceClient struct {
	cc *grpc.ClientConn
}

func NewDependenciesServiceClient(cc *grpc.ClientConn) DependenciesServiceClient {
	return &dependenciesServiceClient{cc}
}

func (c *dependenciesServiceClient) GetDependencies(ctx context.Context, in *DependenciesRequest, opts ...grpc.CallOption) (*DependenciesResponse, error) {
	out := new(DependenciesResponse)
	err := c.cc.Invoke(ctx, "/api.DependenciesService/GetDependencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DependenciesServiceServer is the server API for DependenciesService service.
type DependenciesServiceServer interface {
	GetDependencies(context.Context, *DependenciesRequest) (*DependenciesResponse, error)
}

// UnimplementedDependenciesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDependenciesServiceServer struct {
}

func (*UnimplementedDependenciesServiceServer) GetDependencies(ctx context.Context, req *DependenciesRequest) (*DependenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDependencies not implemented")
}

func RegisterDependenciesServiceServer(s *grpc.Server, srv DependenciesServiceServer) {
	s.RegisterService(&_DependenciesService_serviceDesc, srv)
}

func _DependenciesService_GetDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DependenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependenciesServiceServer).GetDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DependenciesService/GetDependencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependenciesServiceServer).GetDependencies(ctx, req.(*DependenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DependenciesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.DependenciesService",
	HandlerType: (*DependenciesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDependencies",
			Handler:    _DependenciesService_GetDependencies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/api.proto",
}
